export enum profileCard {
    GET_MY_DATA = 'myData/GET_MY_DATA',
    GET_MY_DATA_ASYNC = 'myData/GET_MY_DATA_ASYNC',
}

export enum pmPage {
    ADD_VISITED_USERS_DATA = 'pmPage/ADD_VISITED_USERS_DATA',
    ADD_ALL_REPORS = 'pmPage/ADD_ALL_REPORS',
    ADD_TARGETED_REPORT_ID = 'pmPage/ADD_TARGETED_REPORT_ID',
    DELETE_TARGETED_REPORT_ID = 'pmPage/DELETE_TARGETED_REPORT_ID',
    GET_TASKS_DATA = 'pmPage/GET_TASKS_DATA',
    GET_TASKS_DATA_ASYNC = 'pmPage/GET_TASKS_DATA_ASYNC',
    GET_SINGLE_USER_DATA = 'pmPage/GET_SINGLE_USER_DATA',
    GET_SINGLE_USER_DATA_ASYNC = 'pmPage/GET_SINGLE_USER_DATA_ASYNC',
}
